kind: Service
apiVersion: v1
metadata:
  name:  lamp-ecommerce-service
  labels:
    app: lamp-ecommerce
spec:
  selector:
    app:  lamp-ecommerce
  type:  ClusterIP
  ports:
  - name:  http-port
    port:  80
    targetPort:  8080